services:
    fibe.MainEventService:
        class:  fibe\EventBundle\Services\MainEventService
        arguments: ["@doctrine.orm.entity_manager","@security.context"]

    fibe.CategoryVersionService:
            class:  fibe\EventBundle\Services\CategoryVersionService
            arguments: ["@doctrine.orm.entity_manager","@security.context", "@annotations.reader"]

