services:
    fibe.MainEventService:
        class:  fibe\EventBundle\Services\MainEventService
        arguments: ["@doctrine.orm.entity_manager","@security.context"]

    fibe.CategoryService:
            class:  fibe\EventBundle\Services\CategoryService
            arguments: ["@doctrine.orm.entity_manager","@security.context"]

