<?php

namespace fibe\EventBundle\Repository;

/**
 * MainEventSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 */
class MainEventSettingsRepository extends VEventRepository
{

}
