<?php

namespace Proxies\__CG__\fibe\Bundle\WWWConfBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ConfEvent extends \fibe\Bundle\WWWConfBundle\Entity\ConfEvent implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'parent', 'children', 'slidePresentation', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'conference', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'papers', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'topics', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'roles', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'isAllDay', 'acronym', 'attach', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'isMainConfEvent', 'slug', 'isInstant', 'isTransparent', 'endAt', 'priority', 'resources', 'duration', 'id', 'createdAt', 'startAt', 'lastModifiedAt', 'summary', 'description', 'comment', 'url', 'organizer', 'revisionSequence', 'attendees', 'contacts', 'classification', 'xProperties', 'status', 'location', 'categories', 'attachs');
        }

        return array('__isInitialized__', 'parent', 'children', 'slidePresentation', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'conference', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'papers', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'topics', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'roles', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'isAllDay', 'acronym', 'attach', '' . "\0" . 'fibe\\Bundle\\WWWConfBundle\\Entity\\ConfEvent' . "\0" . 'isMainConfEvent', 'slug', 'isInstant', 'isTransparent', 'endAt', 'priority', 'resources', 'duration', 'id', 'createdAt', 'startAt', 'lastModifiedAt', 'summary', 'description', 'comment', 'url', 'organizer', 'revisionSequence', 'attendees', 'contacts', 'classification', 'xProperties', 'status', 'location', 'categories', 'attachs');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ConfEvent $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function slugify()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'slugify', array());

        return parent::slugify();
    }

    /**
     * {@inheritDoc}
     */
    public function onUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onUpdate', array());

        return parent::onUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function fitChildrenDate($allDay = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fitChildrenDate', array($allDay));

        return parent::fitChildrenDate($allDay);
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function computeIsAllDay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'computeIsAllDay', array());

        return parent::computeIsAllDay();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlidePresentation($slidePresentation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlidePresentation', array($slidePresentation));

        return parent::setSlidePresentation($slidePresentation);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlidePresentation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlidePresentation', array());

        return parent::getSlidePresentation();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttach($attach)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttach', array($attach));

        return parent::setAttach($attach);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttach', array());

        return parent::getAttach();
    }

    /**
     * {@inheritDoc}
     */
    public function setConference(\fibe\Bundle\WWWConfBundle\Entity\WwwConf $conference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConference', array($conference));

        return parent::setConference($conference);
    }

    /**
     * {@inheritDoc}
     */
    public function getConference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConference', array());

        return parent::getConference();
    }

    /**
     * {@inheritDoc}
     */
    public function addPaper(\fibe\Bundle\WWWConfBundle\Entity\Paper $papers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPaper', array($papers));

        return parent::addPaper($papers);
    }

    /**
     * {@inheritDoc}
     */
    public function removePaper(\fibe\Bundle\WWWConfBundle\Entity\Paper $papers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePaper', array($papers));

        return parent::removePaper($papers);
    }

    /**
     * {@inheritDoc}
     */
    public function getPapers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPapers', array());

        return parent::getPapers();
    }

    /**
     * {@inheritDoc}
     */
    public function addTopic(\fibe\Bundle\WWWConfBundle\Entity\Topic $topics)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTopic', array($topics));

        return parent::addTopic($topics);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTopic(\fibe\Bundle\WWWConfBundle\Entity\Topic $topics)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTopic', array($topics));

        return parent::removeTopic($topics);
    }

    /**
     * {@inheritDoc}
     */
    public function getTopics()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTopics', array());

        return parent::getTopics();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole(\fibe\Bundle\WWWConfBundle\Entity\Role $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', array($roles));

        return parent::addRole($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole(\fibe\Bundle\WWWConfBundle\Entity\Role $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', array($roles));

        return parent::removeRole($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsAllDay($isAllDay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsAllDay', array($isAllDay));

        return parent::setIsAllDay($isAllDay);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsAllDay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsAllDay', array());

        return parent::getIsAllDay();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMainConfEvent($isMainConfEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMainConfEvent', array($isMainConfEvent));

        return parent::setIsMainConfEvent($isMainConfEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsMainConfEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsMainConfEvent', array());

        return parent::getIsMainConfEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsInstant($isInstant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsInstant', array($isInstant));

        return parent::setIsInstant($isInstant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsInstant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsInstant', array());

        return parent::getIsInstant();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcronym($acronym)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcronym', array($acronym));

        return parent::setAcronym($acronym);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcronym()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcronym', array());

        return parent::getAcronym();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\fibe\Bundle\WWWConfBundle\Entity\ConfEvent $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', array($parent));

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', array());

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function addChildren(\fibe\Bundle\WWWConfBundle\Entity\ConfEvent $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChildren', array($children));

        return parent::addChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChildren(\fibe\Bundle\WWWConfBundle\Entity\ConfEvent $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChildren', array($children));

        return parent::removeChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', array());

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function hasChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasChildren', array());

        return parent::hasChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function computeEndAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'computeEndAt', array());

        return parent::computeEndAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsTransparent($isTransparent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsTransparent', array($isTransparent));

        return parent::setIsTransparent($isTransparent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsTransparent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsTransparent', array());

        return parent::getIsTransparent();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndAt($endAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndAt', array($endAt));

        return parent::setEndAt($endAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndAt', array());

        return parent::getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    public function hasGeo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasGeo', array());

        return parent::hasGeo();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeoLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeoLatitude', array());

        return parent::getGeoLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeoLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeoLongitude', array());

        return parent::getGeoLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriority($priority)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriority', array($priority));

        return parent::setPriority($priority);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriority()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriority', array());

        return parent::getPriority();
    }

    /**
     * {@inheritDoc}
     */
    public function setResources($resources)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResources', array($resources));

        return parent::setResources($resources);
    }

    /**
     * {@inheritDoc}
     */
    public function getResources()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResources', array());

        return parent::getResources();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration($duration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', array($duration));

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', array());

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function upRevisionSequence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upRevisionSequence', array());

        return parent::upRevisionSequence();
    }

    /**
     * {@inheritDoc}
     */
    public function onCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onCreation', array());

        return parent::onCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function getUID($domain = 'default')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUID', array($domain));

        return parent::getUID($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptions', array());

        return parent::getOptions();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormatedStartAt($format = 'D, d M Y H:i:s O', $timezone = 'Europe/Paris')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormatedStartAt', array($format, $timezone));

        return parent::getFormatedStartAt($format, $timezone);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartAt($startAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartAt', array($startAt));

        return parent::setStartAt($startAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartAt', array());

        return parent::getStartAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastModifiedAt($lastModifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastModifiedAt', array($lastModifiedAt));

        return parent::setLastModifiedAt($lastModifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastModifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastModifiedAt', array());

        return parent::getLastModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSummary($summary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSummary', array($summary));

        return parent::setSummary($summary);
    }

    /**
     * {@inheritDoc}
     */
    public function getSummary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSummary', array());

        return parent::getSummary();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', array($comment));

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', array());

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganizer($organizer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganizer', array($organizer));

        return parent::setOrganizer($organizer);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizer', array());

        return parent::getOrganizer();
    }

    /**
     * {@inheritDoc}
     */
    public function setRevisionSequence($revisionSequence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevisionSequence', array($revisionSequence));

        return parent::setRevisionSequence($revisionSequence);
    }

    /**
     * {@inheritDoc}
     */
    public function getRevisionSequence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevisionSequence', array());

        return parent::getRevisionSequence();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttendees($attendees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttendees', array($attendees));

        return parent::setAttendees($attendees);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendees', array());

        return parent::getAttendees();
    }

    /**
     * {@inheritDoc}
     */
    public function setContacts($contacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContacts', array($contacts));

        return parent::setContacts($contacts);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', array());

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassification($classification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassification', array($classification));

        return parent::setClassification($classification);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassification', array());

        return parent::getClassification();
    }

    /**
     * {@inheritDoc}
     */
    public function addXPropertie(\fibe\Bundle\WWWConfBundle\Entity\XProperty $xProperties)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addXPropertie', array($xProperties));

        return parent::addXPropertie($xProperties);
    }

    /**
     * {@inheritDoc}
     */
    public function removeXPropertie(\fibe\Bundle\WWWConfBundle\Entity\XProperty $xProperties)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeXPropertie', array($xProperties));

        return parent::removeXPropertie($xProperties);
    }

    /**
     * {@inheritDoc}
     */
    public function getXProperties()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXProperties', array());

        return parent::getXProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\fibe\Bundle\WWWConfBundle\Entity\Status $status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(\fibe\Bundle\WWWConfBundle\Entity\Location $location = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', array($location));

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', array());

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategorie(\fibe\Bundle\WWWConfBundle\Entity\Category $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategorie', array($categories));

        return parent::addCategorie($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategorie(\fibe\Bundle\WWWConfBundle\Entity\Category $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategorie', array($categories));

        return parent::removeCategorie($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', array());

        return parent::getCategories();
    }

}
