organization:
    type: rest
    resource: fibe\CommunityBundle\Controller\REST\CompanyRESTController
    name_prefix: api_

person:
    type: rest
    resource: fibe\CommunityBundle\Controller\REST\PersonRESTController
    name_prefix: api_
