<?php

/**
 *
 * @author :  Gabriel BONDAZ <gabriel.bondaz@idci-consulting.fr>
 * @licence: GPL
 *
 */

namespace fibe\ContentBundle\Repository;

use Doctrine\ORM\EntityRepository;
use fibe\ContentBundle\Entity\Equipment;
use fibe\ContentBundle\Entity\Location;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 */
class EquipmentRepository extends EntityRepository
{

    /**
     * filtering by main event
     * @param $qb , query builder to add the filter to
     * @param $MainEventId , the main event to filter on
     * @return $qb, modified query builder
     */
    public function findAllByMainEventId($qb, $MainEventId)
    {
        if (isset($MainEventId)) {
            $qb->leftJoin('qb.locations', 'l');
            $qb->leftJoin('l.mainEvent', 'ev');
            $qb->andWhere('ev.id = (:MainEventId)');
            $qb->setParameter('MainEventId', $MainEventId);
        }
        return $qb;
    }
}