<?php

namespace fibe\ContentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleLabelRepository extends EntityRepository
{


}
