services:
    mainEventService:
        class:  fibe\ConferenceBundle\Services\MainEventService
        arguments: ["@doctrine.orm.entity_manager"]

idci_exporter:
    entities:
        MainEvent:
            class: "fibe\\Bundle\\WWWConfBundle\\Entity\\MainEvent"
            formats:
                xml:
                    transformer:
                        service: "idci_exporter.transformer_twig"
                        options: 
                            template_name_format: "export.xml.twig"

