services:
    emptyConf:
        class:  fibe\ConferenceBundle\Services\EmptyConf

idci_exporter:
    entities:
        MainEvent:
            class: "fibe\\Bundle\\WWWConfBundle\\Entity\\MainEvent"
            formats:
                xml:
                    transformer:
                        service: "idci_exporter.transformer_twig"
                        options: 
                            template_name_format: "export.xml.twig"

