<?php

namespace fibe\MobileAppBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MobileAppThemeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \fibe\MobileAppBundle\Controller\MobileAppThemeController();
        return $instance;
    }
}
