<?php

namespace fibe\DocumentationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DocumentationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \fibe\DocumentationBundle\Controller\DocumentationController();
        return $instance;
    }
}
