<?php

namespace fibe\Bundle\WWWConfBundle\Controller\REST;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PersonRESTController__JMSInjector
{
    public static function inject($container) {
        $instance = new \fibe\Bundle\WWWConfBundle\Controller\REST\PersonRESTController();
        return $instance;
    }
}
