<?php

namespace fibe\ConferenceBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ExportController__JMSInjector
{
    public static function inject($container) {
        $instance = new \fibe\ConferenceBundle\Controller\ExportController();
        return $instance;
    }
}
