<?php

namespace fibe\SecurityBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EnrichAccountController__JMSInjector
{
    public static function inject($container) {
        $instance = new \fibe\SecurityBundle\Controller\EnrichAccountController();
        return $instance;
    }
}
