<?php

namespace fibe\DataBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DataController__JMSInjector
{
    public static function inject($container) {
        $instance = new \fibe\DataBundle\Controller\DataController();
        return $instance;
    }
}
