<?php

namespace fibe\Bundle\WWWConfBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PaperController__JMSInjector
{
    public static function inject($container) {
        $instance = new \fibe\Bundle\WWWConfBundle\Controller\PaperController();
        return $instance;
    }
}
