<?php

namespace fibe\FrontendBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FrontController__JMSInjector
{
    public static function inject($container) {
        $instance = new \fibe\FrontendBundle\Controller\FrontController();
        return $instance;
    }
}
