<?php

namespace fibe\HomePageBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HomePageController__JMSInjector
{
    public static function inject($container) {
        $instance = new \fibe\HomePageBundle\Controller\HomePageController();
        return $instance;
    }
}
